config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
resources :quotes
root 'welcome#index'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/quote.rb
class Quote < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  def index
  @quotes = Quote.all
  end
  
def show
@quote = Quote.find(params[:id])
end

def new
end

def create
@quote = Quote.new(quote_params)

@quote.save
redirect_to :root
end

private
def quote_params
params.require(:quote).permit(:text)
end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  @quotes = Quote.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/quotes/new.html.erb
<h1>Add Quote</h1>


<%= form_with scope: :quote, url: quotes_path, local: true do |form| %>

  <p>
    <%= form.label :text %><br>
    <%= form.text_area :text %>
  </p>
 
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/quotes/show.html.erb
<p>
<strong>Text:</strong>
<%=@quote.text %>
</p>

app/views/welcome/index.html.erb
<h1> All Quotes</h1>

<%= link_to 'Add Quote', new_quote_path %>




<table>
 
 
  <% @quotes.each do |quote| %>
    <tr>
      <td><%= quote.text %></td>
    </tr>
  <% end %>
</table>